// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {  
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQUvotuR8kOOUvk6XCUg3whRTTvNZMYg',
    appId: '1:179973123196:web:1936fc63eb216189ca2df9',
    messagingSenderId: '179973123196',
    projectId: 'fir-1f0aa',
    authDomain: 'fir-1f0aa.firebaseapp.com',
    storageBucket: 'fir-1f0aa.appspot.com',
    measurementId: 'G-WTWMEQ75GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO7h6Q_mYU802UGXiXOhKd1hIm-PIxwSc',
    appId: '1:179973123196:android:b0327c6750a86055ca2df9',
    messagingSenderId: '179973123196',
    projectId: 'fir-1f0aa',
    storageBucket: 'fir-1f0aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFRSH1t6GcBxdcLMRhTX8l42ygdKUzhzY',
    appId: '1:179973123196:ios:693693824b45f719ca2df9',
    messagingSenderId: '179973123196',
    projectId: 'fir-1f0aa',
    storageBucket: 'fir-1f0aa.appspot.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFRSH1t6GcBxdcLMRhTX8l42ygdKUzhzY',
    appId: '1:179973123196:ios:ddca6dfbfea02e3cca2df9',
    messagingSenderId: '179973123196',
    projectId: 'fir-1f0aa',
    storageBucket: 'fir-1f0aa.appspot.com',
    iosBundleId: 'com.example.eshop.RunnerTests',
  );
}
